version: "3"

services:
    DBAdminBot-frontend:
        shm_size: 4gb
        image: hyukkyukang/sqlbot:latest
        container_name: DBAdminBot-frontend
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./demo/dbadminbot/frontend:/root/dbadminbot

    DBAdminBot-backend:
        shm_size: 4gb
        image: hyukkyukang/nl2qgm:latest
        container_name: DBAdminBot-backend
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./demo/dbadminbot/backend:/root/dbadminbot/
            - ./source:/root/dbadminbot/source
            - redis_data:/root/dbadminbot/data/redis/
            - /mnt:/mnt
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    DBadminBot-redis:
        image: redis:latest
        container_name: DBadminBot-redis
        volumes:
            - redis_data:/data
        ports:
            - target: 6379
              published: 6379
        networks:
            - redis

    DBAdminBot-AnomalyExp:
        shm_size: 4gb
        image: hyukkyukang/anomaly_explanation:v2
        container_name: DBAdminBot-AnomalyExp
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro 
            - ./source/diagnosis/detection/Anomaly_Explanation:/root/Anomaly_Explanation
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

volumes:
    redis_data:
        driver: local

networks:
    redis:
        driver: bridge
