version: "3"

services:
    DBAdminBot-frontend:
        shm_size: 4gb
        image: hyukkyukang/sqlbot:latest
        container_name: DBAdminBot-frontend
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./web/dbadminbot:/root/dbadminbot

    DBAdminBot-backend:
        shm_size: 4gb
        image: hyukkyukang/nl2qgm:latest
        container_name: DBAdminBot-backend
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./:/root/dbadminbot/
            - redis_data:/root/dbadminbot/data/redis/
            - /mnt:/mnt
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    DBAdminBot-redis:
        image: redis:latest
        container_name: DBAdminBot-redis
        network_mode: "host"  # Changed from bridge to host
        volumes:
            - redis_data:/data
        command: redis-server --port 6380  # Explicitly set port
        # Remove the ports section when using host network

volumes:
    redis_data:
        driver: local